"""add_event_coordinates

Revision ID: dd192fecc0c6
Revises: 61f4d390e52f
Create Date: 2026-07-09 04:47:07.097615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd192fecc0c6"
down_revision: Union[str, Sequence[str], None] = "61f4d390e52f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as NOT NULL with a server_default so existing rows are backfilled
    # atomically instead of the migration failing against a populated table.
    op.add_column(
        "events",
        sa.Column("latitude", sa.Float(), nullable=False, server_default="0"),
    )
    op.add_column(
        "events",
        sa.Column("longitude", sa.Float(), nullable=False, server_default="0"),
    )
    # Drop the default afterwards: new rows must supply real coordinates.
    op.alter_column("events", "latitude", server_default=None)
    op.alter_column("events", "longitude", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "longitude")
    op.drop_column("events", "latitude")
    # ### end Alembic commands ###
