"""add_event_coordinates

Revision ID: dd192fecc0c6
Revises: 61f4d390e52f
Create Date: 2026-07-09 04:47:07.097615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd192fecc0c6"
down_revision: Union[str, Sequence[str], None] = "61f4d390e52f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("latitude", sa.Float(), nullable=False))
    op.add_column("events", sa.Column("longitude", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "longitude")
    op.drop_column("events", "latitude")
    # ### end Alembic commands ###
