"""Add Stock to Products table

Revision ID: fc2cf7b05360
Revises: d1e2f3a4b5c6
Create Date: 2026-06-19 00:00:21.301480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc2cf7b05360"
down_revision: Union[str, Sequence[str], None] = "d1e2f3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("stock", sa.Integer(), server_default="0", nullable=False)
    )
    op.drop_index(
        op.f("ix_products_description_trgm"),
        table_name="products",
        postgresql_ops={"description": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_products_name_trgm"),
        table_name="products",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_name_trgm"),
        "products",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_products_description_trgm"),
        "products",
        ["description"],
        unique=False,
        postgresql_ops={"description": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("products", "stock")
    # ### end Alembic commands ###
